# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-pull-requests ]
  pull_request:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-pull-requests ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - node-version: 12.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: add chrome
      run: |
        sudo apt-get update
        sudo apt-get --only-upgrade install google-chrome-stable
        google-chrome --version
    - name: Install, build, test
      working-directory: ./ui
      run: |
        npm install
        npm build
        npm run test-headless
