# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python test

on:
  push:
    branches: [ 917-unit-tests-on-python ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ./embedding-calculator/
      run: |
        python -m pip install --upgrade pip
        python -m pip --no-cache-dir install -r requirements.txt -e srcext/insightface/python-package
        imageio_download_bin freeimage
    - name: Test with pytest
      working-directory: ./embedding-calculator/
      run: |
       pip install pytest
       pip install pytest-cov
       SCANNER=Facenet2018 python -m pytest -m "not performance" ./src
