name: Unit tests on maven test

on:
  push:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-maven ]
  pull_request:
    branches: [ efrs-917-github-actions-to-run-unit-tests-on-maven ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn -B clean package
